language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - PYTHON_VERSION="2.7"  PARALLEL="mpich2"  DISTRIB="conda"
    - PYTHON_VERSION="2.7"  PARALLEL="false"   DISTRIB="conda"
    - PYTHON_VERSION="2.6"  PARALLEL="false"   DISTRIB="conda"

install: 
    - source tools/install_packages.sh
    - python setup.py install

script: 
    - python runtests.py

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi

cache: apt



