language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - PYTHON_VERSION="2.7"  PARALLEL="mpich2"  DISTRIB="conda"
    - PYTHON_VERSION="2.7"  PARALLEL="mpich2"  DISTRIB="ubuntu" COVERAGE="--coverage"
    #- PYTHON_VERSION="2.7"  PARALLEL="false"   DISTRIB="conda"
    #- PYTHON_VERSION="2.6"  PARALLEL="false"   DISTRIB="conda"

install: 
    - source tools/install_packages.sh
    - python setup.py install

script: 
    - python runtests.py $COVERAGE
    - if [[ "$COVERAGE" == "--coverage" ]]; then cp build/test/.coverage .; fi

after_success:
    - if [[ "$COVERAGE" == "--coverage" ]]; then coveralls || echo "failed"; fi







