language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - PYTHON_VERSION="2.7"  PARALLEL="openmpi"  DISTRIB="conda"
    #- PYTHON_VERSION="2.7"  PARALLEL="openmpi"  DISTRIB="ubuntu"
    #- PYTHON_VERSION="2.7"  PARALLEL="mpich2"  DISTRIB="conda"
    - PYTHON_VERSION="2.7"  PARALLEL="mpich2"  DISTRIB="ubuntu" COVERAGE="--coverage"
    #- PYTHON_VERSION="2.7"  PARALLEL="false"   DISTRIB="conda"
    #- PYTHON_VERSION="2.6"  PARALLEL="false"   DISTRIB="conda"

install: 
    - if [[ "$DISTRIB"="conda" ]]; then source tools/install_conda.sh; fi
    - if [[ "$DISTRIB"="ubuntu" ]]; then source tools/install_ubuntu.sh; fi

script: 
    - python runtests.py -vv $COVERAGE
    - if [[ "$COVERAGE" == "--coverage" ]]; then cp build/test/.coverage .; fi

after_success:
    - if [[ "$COVERAGE" == "--coverage" ]]; then coveralls || echo "failed"; fi







